#==============================================================================
#   WARNING!!  This file is overwritten by the Block UI Styler while generating
#   the automation code. Any modifications to this file will be lost after
#   generating the code again.
# 
#        Filename:  C:\Users\user\Desktop\NX-3d-models\new_ui.py
# 
#         This file was generated by the NX Block UI Styler
#         Created by: user
#               Version: NX 2406
#==============================================================================

#------------------------------------------------------------------------------
# These imports are needed for the following template code
#------------------------------------------------------------------------------
import NXOpen
import NXOpen.BlockStyler
import subprocess

#------------------------------------------------------------------------------
# Represents Block Styler application cls
#------------------------------------------------------------------------------
class new_ui:
    # static class members
    theSession = None
    theUI = None
    
    #------------------------------------------------------------------------------
    # Constructor for NX Styler class
    #------------------------------------------------------------------------------
    def __init__(self):
        try:
            self.theSession = NXOpen.Session.GetSession()
            self.theUI = NXOpen.UI.GetUI()
            self.theDlxFileName = r"C:\Users\user\Desktop\NX-3d-models\new_ui.dlx"
            self.theDialog = self.theUI.CreateDialog(self.theDlxFileName)
            self.theDialog.AddApplyHandler(self.apply_cb)
            self.theDialog.AddOkHandler(self.ok_cb)
            self.theDialog.AddUpdateHandler(self.update_cb)
            self.theDialog.AddInitializeHandler(self.initialize_cb)
            self.theDialog.AddDialogShownHandler(self.dialogShown_cb)
        except Exception as ex:
            # Только критическая ошибка – показываем окно
            self.theUI.NXMessageBox.Show("Ошибка", NXOpen.NXMessageBox.DialogType.Error, str(ex))
            raise ex
        
    #------------------------------------------------------------------------------
    # This method launches the dialog to screen
    #------------------------------------------------------------------------------
    def Launch(self):
        dialogResponse = NXOpen.BlockStyler.BlockDialog.DialogResponse.Invalid
        try:
            dialogResponse = self.theDialog.Launch()
        except Exception as ex:
            self.theUI.NXMessageBox.Show("Ошибка", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        return dialogResponse
    
    #------------------------------------------------------------------------------
    # Method Name: Dispose
    #------------------------------------------------------------------------------
    def Dispose(self):
        if self.theDialog != None:
            self.theDialog.Dispose()
            self.theDialog = None
    
    #------------------------------------------------------------------------------
    # Callback Name: initialize_cb
    #------------------------------------------------------------------------------
    def initialize_cb(self):
        try:
            self.group0 = self.theDialog.TopBlock.FindBlock("group0")
            self.multiline_string0 = self.theDialog.TopBlock.FindBlock("multiline_string0")
            self.button0 = self.theDialog.TopBlock.FindBlock("button0")
        except Exception as ex:
            self.theUI.NXMessageBox.Show("Ошибка", NXOpen.NXMessageBox.DialogType.Error, str(ex))
    
    #------------------------------------------------------------------------------
    # Callback Name: dialogShown_cb
    #------------------------------------------------------------------------------
    def dialogShown_cb(self):
        pass
    
    #------------------------------------------------------------------------------
    # Callback Name: apply_cb
    #------------------------------------------------------------------------------
    def apply_cb(self):
        errorCode = 0
        try:
            pass
        except Exception as ex:
            errorCode = 1
            self.theUI.NXMessageBox.Show("Ошибка", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        return errorCode
    
    #------------------------------------------------------------------------------
    # Helper: вывод сообщения в Listing Window
    #------------------------------------------------------------------------------
    def show_in_listing(self, text: str):
        listing = self.theSession.ListingWindow
        listing.Open()
        listing.WriteLine("=" * 80)
        listing.WriteLine("Ошибка генерации модели")
        listing.WriteLine("=" * 80)
        listing.WriteLine(text)
        listing.WriteLine("=" * 80)
        listing.Close()  # закрываем после записи, окно останется открытым

    #------------------------------------------------------------------------------
    # Callback Name: update_cb
    #------------------------------------------------------------------------------
    def update_cb(self, block):
        try:
            if block == self.multiline_string0:
                pass
            elif block == self.button0:
                try:
                    lines = self.multiline_string0.GetValue()
                    user_request = "\n".join(lines).strip() if lines else ""

                    if not user_request:
                        return 0

                    python_exe = r"C:\Users\user\AppData\Local\Programs\Python\Python313\python.exe"
                    generate_script = r"C:\Users\user\Desktop\NX-3d-models\generate.py"
                    result_path = r"C:\Users\user\Desktop\NX-3d-models\generated\result.py"

                    proc = subprocess.run(
                        [python_exe, generate_script, user_request],
                        capture_output=True, text=True, encoding="utf-8", errors="replace",
                        timeout=900
                    )

                    if proc.returncode != 0:
                        # Ошибка генерации – выводим stderr в Listing Window
                        self.show_in_listing(proc.stderr)
                        return 0

                    # Генерация успешна, выполняем код
                    with open(result_path, "r", encoding="utf-8") as f:
                        code = f.read()
                    exec(code, {})

                    # Успех – никаких сообщений

                except subprocess.TimeoutExpired:
                    self.show_in_listing("Превышено время ожидания генерации (900 сек)")
                except Exception as ex:
                    # Любая другая ошибка (в том числе exec) – выводим детали
                    self.show_in_listing(f"Ошибка выполнения:\n{str(ex)}")
        except Exception as ex:
            # Общая ошибка в callback – выводим в Listing Window
            self.show_in_listing(f"Общая ошибка:\n{str(ex)}")
        return 0
    
    #------------------------------------------------------------------------------
    # Callback Name: ok_cb
    #------------------------------------------------------------------------------
    def ok_cb(self):
        errorCode = 0
        try:
            errorCode = self.apply_cb()
        except Exception as ex:
            errorCode = 1
            self.theUI.NXMessageBox.Show("Ошибка", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        return errorCode
    
    #------------------------------------------------------------------------------
    # Function Name: GetBlockProperties
    #------------------------------------------------------------------------------
    def GetBlockProperties(self, blockID):
        try:
            return self.theDialog.GetBlockProperties(blockID)
        except Exception as ex:
            self.theUI.NXMessageBox.Show("Ошибка", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        return None
    
def main():
    thenew_ui = None
    try:
        thenew_ui = new_ui()
        thenew_ui.Launch()
    except Exception as ex:
        NXOpen.UI.GetUI().NXMessageBox.Show("Ошибка", NXOpen.NXMessageBox.DialogType.Error, str(ex))
    finally:
        if thenew_ui != None:
            thenew_ui.Dispose()
            thenew_ui = None
    
if __name__ == '__main__':
    main()