#==============================================================================
#   WARNING!!  This file is overwritten by the Block UI Styler while generating
#   the automation code. Any modifications to this file will be lost after
#   generating the code again.
#
#        Filename:  C:\Users\user\Desktop\NX-3d-models\new_ui.py
#
#         This file was generated by the NX Block UI Styler
#         Created by: user
#               Version: NX 2406
#==============================================================================

#------------------------------------------------------------------------------
# These imports are needed for the following template code
#------------------------------------------------------------------------------
import NXOpen
import NXOpen.BlockStyler
import subprocess
import json
import os
from pathlib import Path

# --- НАСТРОЙКИ ПОД КОНКРЕТНУЮ МАШИНУ (проверить при переносе проекта) ------
PROJECT_ROOT = str(Path(__file__).resolve().parent)
PYTHON_EXE = r"C:\Users\user\AppData\Local\Microsoft\WindowsApps\python.exe"
# PYTHON_EXE = r"C:\Users\user\AppData\Local\Programs\Python\Python313\python.exe"
GENERATE_SCRIPT = PROJECT_ROOT + r"\generate.py"
RESULT_PATH = PROJECT_ROOT + r"\generated\result.py"
# Единый файл контекста для generate.py: может содержать error/code (ретрай
# после ошибки в NX) и/или history (переключатель "Отправить в тот же чат")
CONTEXT_FILE = PROJECT_ROOT + r"\generated\prev_nx_context.json"

# Сколько последних успешных турнов диалога храним в памяти при включённом
# "Отправить в тот же чат" (совпадает с MAX_HISTORY_TURNS в run.py)
MAX_HISTORY_TURNS = 3

MAX_NX_ATTEMPTS = 3  # сколько раз пробуем перегенерировать после ошибки в NX

# Таймаут одного subprocess-вызова generate.py. Внутри run_generation —
# до DEFAULT_MAX_ATTEMPTS (3) попыток по 400с таймаута ollama = максимум
# ~1200с на статическую валидацию, плюс запас на IO/валидацию/build_prompt.
GENERATE_SUBPROCESS_TIMEOUT = 1400
# ------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Represents Block Styler application cls
#------------------------------------------------------------------------------
class new_ui:
    # static class members
    theSession = None
    theUI = None

    #------------------------------------------------------------------------------
    # Constructor for NX Styler class
    #------------------------------------------------------------------------------
    def __init__(self):
        try:
            self.theSession = NXOpen.Session.GetSession()
            self.theUI = NXOpen.UI.GetUI()
            self.theDlxFileName = PROJECT_ROOT + r"\new_ui.dlx"
            self.theDialog = self.theUI.CreateDialog(self.theDlxFileName)
            self.theDialog.AddOkHandler(self.ok_cb)
            self.theDialog.AddUpdateHandler(self.update_cb)
            self.theDialog.AddInitializeHandler(self.initialize_cb)
            self.theDialog.AddDialogShownHandler(self.dialogShown_cb)

            # история успешных турнов "того же чата" между нажатиями кнопки,
            # пока диалог открыт (см. toggle0 / MAX_HISTORY_TURNS)
            self.chat_history = []
        except Exception as ex:
            self.theUI.NXMessageBox.Show("Ошибка", NXOpen.NXMessageBox.DialogType.Error, str(ex))
            raise ex

    #------------------------------------------------------------------------------
    # This method launches the dialog to screen
    #------------------------------------------------------------------------------
    def Launch(self):
        dialogResponse = NXOpen.BlockStyler.BlockDialog.DialogResponse.Invalid
        try:
            dialogResponse = self.theDialog.Launch()
        except Exception as ex:
            self.theUI.NXMessageBox.Show("Ошибка", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        return dialogResponse

    #------------------------------------------------------------------------------
    # Method Name: Dispose
    #------------------------------------------------------------------------------
    def Dispose(self):
        if self.theDialog != None:
            self.theDialog.Dispose()
            self.theDialog = None

    #------------------------------------------------------------------------------
    # Callback Name: initialize_cb
    #------------------------------------------------------------------------------
    def initialize_cb(self):
        try:
            self.group0 = self.theDialog.TopBlock.FindBlock("group0")
            self.toggle0 = self.theDialog.TopBlock.FindBlock("toggle0")
            self.multiline_string0 = self.theDialog.TopBlock.FindBlock("multiline_string0")
            self.button01 = self.theDialog.TopBlock.FindBlock("button01")
            self.button0 = self.theDialog.TopBlock.FindBlock("button0")
        except Exception as ex:
            self.theUI.NXMessageBox.Show("Ошибка", NXOpen.NXMessageBox.DialogType.Error, str(ex))

    #------------------------------------------------------------------------------
    # Callback Name: dialogShown_cb
    #------------------------------------------------------------------------------
    def dialogShown_cb(self):
        pass

    #------------------------------------------------------------------------------
    # Helper: вывод сообщения в Listing Window
    #------------------------------------------------------------------------------
    def show_in_listing(self, text: str):
        listing = self.theSession.ListingWindow
        listing.Open()
        listing.WriteLine("=" * 80)
        listing.WriteLine("Ошибка генерации модели")
        listing.WriteLine("=" * 80)
        listing.WriteLine(text)
        listing.WriteLine("=" * 80)
        listing.Close()  # закрываем после записи, окно останется открытым

    #------------------------------------------------------------------------------
    # Helper: полная очистка холста — все тела, эскизы, datum-объекты
    #------------------------------------------------------------------------------
    def clear_canvas(self):
        workPart = self.theSession.Parts.Work
        if workPart is None:
            return

        objects_to_delete = []
        objects_to_delete.extend(list(workPart.Bodies))     # солиды и листовые тела
        objects_to_delete.extend(list(workPart.Sketches))    # эскизы
        objects_to_delete.extend(list(workPart.Datums))      # плоскости/оси/CSYS
        objects_to_delete.extend(list(workPart.Curves))      # "сырые" линии, дуги, сплайны вне эскизов

        if not objects_to_delete:
            return

        markId = self.theSession.SetUndoMark(
            NXOpen.Session.MarkVisibility.Invisible, "Очистить всё"
        )
        try:
            self.theSession.UpdateManager.AddToDeleteList(objects_to_delete)
            self.theSession.UpdateManager.DoUpdate(markId)
        except Exception as ex:
            self.theSession.UndoToMark(markId, "Очистить всё")
            self.show_in_listing(f"Ошибка очистки холста:\n{str(ex)}")

    #------------------------------------------------------------------------------
    # Callback Name: update_cb
    #------------------------------------------------------------------------------
    def update_cb(self, block):
        try:
            if block == self.toggle0:
                # ничего не делаем прямо сейчас — значение читаем в момент нажатия button0
                pass

            elif block == self.multiline_string0:
                pass

            elif block == self.button01:
                # "Очистить все" — сносим всю геометрию с холста
                try:
                    self.clear_canvas()
                    self.chat_history = []
                    self.multiline_string0.SetValue([""])
                except Exception as ex:
                    self.show_in_listing(f"Ошибка очистки:\n{str(ex)}")

            elif block == self.button0:
                try:
                    lines = self.multiline_string0.GetValue()
                    user_request = "\n".join(lines).strip() if lines else ""

                    if not user_request:
                        return 0

                    same_chat = bool(self.toggle0.Value)
                    if same_chat:
                        self.clear_canvas()
                    prev_error_text = None   # ошибка исполнения с предыдущей итерации
                    prev_code_text = None    # код, который реально исполнялся и упал

                    for attempt in range(1, MAX_NX_ATTEMPTS + 1):

                        # --- шаг 1: генерация (в отдельном не-NX процессе) ---
                        args = [PYTHON_EXE, GENERATE_SCRIPT, user_request]

                        # Собираем единый файл контекста: ошибка исполнения в NX (если
                        # это повторная попытка) и/или история "того же чата" (если
                        # включён toggle0). Пишем через JSON-файл, а не argv — traceback
                        # и код содержат кавычки/переносы строк.
                        context_data = {}
                        if prev_error_text:
                            context_data["error"] = prev_error_text
                            context_data["code"] = prev_code_text or ""
                        if same_chat and self.chat_history:
                            context_data["history"] = self.chat_history

                        if context_data:
                            with open(CONTEXT_FILE, "w", encoding="utf-8") as f:
                                json.dump(context_data, f, ensure_ascii=False)
                            args.append(CONTEXT_FILE)

                        env = os.environ.copy()
                        env["PYTHONIOENCODING"] = "utf-8"
                        env["PYTHONUTF8"] = "1"

                        proc = subprocess.run(
                            args,
                            capture_output=True, text=True, encoding="utf-8", errors="replace",
                            timeout=GENERATE_SUBPROCESS_TIMEOUT,
                            env=env,
                        )

                        if proc.returncode != 0:
                            # генератор не смог выдать даже статически валидный код —
                            # дальше по NX-retry идти бессмысленно, показываем ошибку сразу
                            self.show_in_listing(proc.stderr)
                            return 0

                        # --- шаг 2: реальное исполнение в NX (только здесь есть NXOpen) ---
                        with open(RESULT_PATH, "r", encoding="utf-8") as f:
                            code = f.read()

                        # Холст должен быть пуст перед КАЖДЫМ exec: перед первой
                        # попыткой — это могла быть старая модель с прошлого нажатия
                        # button0; перед retry — частично построенные тела из
                        # предыдущей упавшей попытки этого же цикла. continuation-
                        # промпт (_continuation_prompt) уже рассчитан на пустой холст
                        # и полную пересборку геометрии из chat_history, так что
                        # очистка тут ничего не ломает даже при same_chat=True.
                        try:
                            self.clear_canvas()
                        except Exception as ex:
                            self.show_in_listing(f"Ошибка очистки холста перед построением:\n{str(ex)}")
                            return 0

                        try:
                            exec(code, {})
                            # Успех — запоминаем этот турн ВСЕГДА, независимо от
                            # состояния toggle0. Тогл влияет только на то, будет ли
                            # эта история ОТПРАВЛЕНА в следующий раз (см. сборку
                            # context_data выше) — сама история копится постоянно,
                            # чтобы включение "того же чата" в любой момент сразу
                            # подхватывало всё, что уже построено в этой сессии.
                            self.chat_history.append({"request": user_request, "code": code})
                            self.chat_history = self.chat_history[-MAX_HISTORY_TURNS:]
                            # никаких сообщений, выходим из цикла и из callback
                            return 0
                        except Exception as ex:
                            prev_error_text = f"{type(ex).__name__}: {ex}"
                            prev_code_text = code  # именно тот код, что упал — для retry
                            if attempt == MAX_NX_ATTEMPTS:
                                self.show_in_listing(
                                    f"Ошибка выполнения (после {MAX_NX_ATTEMPTS} попыток):\n{prev_error_text}"
                                )
                            # иначе — молча уходим на следующую итерацию цикла (retry)

                except subprocess.TimeoutExpired:
                    self.show_in_listing(f"Превышено время ожидания генерации ({GENERATE_SUBPROCESS_TIMEOUT} сек)")
                except Exception as ex:
                    self.show_in_listing(f"Ошибка выполнения:\n{str(ex)}")

        except Exception as ex:
            self.show_in_listing(f"Общая ошибка:\n{str(ex)}")
        return 0

    #------------------------------------------------------------------------------
    # Callback Name: ok_cb
    #------------------------------------------------------------------------------
    def ok_cb(self):
        errorCode = 0
        try:
            pass
        except Exception as ex:
            errorCode = 1
            self.theUI.NXMessageBox.Show("Ошибка", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        return errorCode

    #------------------------------------------------------------------------------
    # Function Name: GetBlockProperties
    #------------------------------------------------------------------------------
    def GetBlockProperties(self, blockID):
        try:
            return self.theDialog.GetBlockProperties(blockID)
        except Exception as ex:
            self.theUI.NXMessageBox.Show("Ошибка", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        return None

def main():
    thenew_ui = None
    try:
        thenew_ui = new_ui()
        thenew_ui.Launch()
    except Exception as ex:
        NXOpen.UI.GetUI().NXMessageBox.Show("Ошибка", NXOpen.NXMessageBox.DialogType.Error, str(ex))
    finally:
        if thenew_ui != None:
            thenew_ui.Dispose()
            thenew_ui = None

if __name__ == '__main__':
    main()