#==============================================================================
#   WARNING!!  This file is overwritten by the Block UI Styler while generating
#   the automation code. Any modifications to this file will be lost after
#   generating the code again.
# 
#        Filename:  C:\Users\user\Desktop\NX-3d-models\new_ui.py
# 
#         This file was generated by the NX Block UI Styler
#         Created by: user
#               Version: NX 2406
#==============================================================================

#------------------------------------------------------------------------------
# These imports are needed for the following template code
#------------------------------------------------------------------------------
import NXOpen
import NXOpen.BlockStyler
import subprocess

#------------------------------------------------------------------------------
# Represents Block Styler application cls
#------------------------------------------------------------------------------
class new_ui:
    # static class members
    theSession = None
    theUI = None
    
    #------------------------------------------------------------------------------
    # Constructor for NX Styler class
    #------------------------------------------------------------------------------
    def __init__(self):
        try:
            self.theSession = NXOpen.Session.GetSession()
            self.theUI = NXOpen.UI.GetUI()
            self.theDlxFileName = r"C:\Users\user\Desktop\NX-3d-models\new_ui.dlx"
            self.theDialog = self.theUI.CreateDialog(self.theDlxFileName)
            self.theDialog.AddApplyHandler(self.apply_cb)
            self.theDialog.AddOkHandler(self.ok_cb)
            self.theDialog.AddUpdateHandler(self.update_cb)
            self.theDialog.AddInitializeHandler(self.initialize_cb)
            self.theDialog.AddDialogShownHandler(self.dialogShown_cb)
        except Exception as ex:
            raise ex
        
    
    #------------------------------------------------------------------------------
    # This method launches the dialog to screen
    #------------------------------------------------------------------------------
    def Launch(self):
        dialogResponse = NXOpen.BlockStyler.BlockDialog.DialogResponse.Invalid
        try:
            dialogResponse = self.theDialog.Launch()
        except Exception as ex:
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return dialogResponse
    
    #------------------------------------------------------------------------------
    # Method Name: Dispose
    #------------------------------------------------------------------------------
    def Dispose(self):
        if self.theDialog != None:
            self.theDialog.Dispose()
            self.theDialog = None
    
    #------------------------------------------------------------------------------
    # Callback Name: initialize_cb
    #------------------------------------------------------------------------------
    def initialize_cb(self):
        try:
            self.group0 = self.theDialog.TopBlock.FindBlock("group0")
            self.multiline_string0 = self.theDialog.TopBlock.FindBlock("multiline_string0")
            self.button0 = self.theDialog.TopBlock.FindBlock("button0")
        except Exception as ex:
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
    
    #------------------------------------------------------------------------------
    # Callback Name: dialogShown_cb
    #------------------------------------------------------------------------------
    def dialogShown_cb(self):
        try:
            pass
        except Exception as ex:
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
    
    #------------------------------------------------------------------------------
    # Callback Name: apply_cb
    #------------------------------------------------------------------------------
    def apply_cb(self):
        errorCode = 0
        try:
            pass
        except Exception as ex:
            errorCode = 1
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return errorCode
    
    #------------------------------------------------------------------------------
    # Callback Name: update_cb
    #------------------------------------------------------------------------------
    def update_cb(self, block):
        try:
            if block == self.multiline_string0:
                pass
            elif block == self.button0:
                try:
                    # MultilineString не имеет .Value - у него метод GetValue(),
                    # который возвращает список строк (по одной на строку ввода)
                    lines = self.multiline_string0.GetValue()
                    user_request = "\n".join(lines).strip() if lines else ""

                    if not user_request:
                        self.theUI.NXMessageBox.Show(
                            "NX AI Generator", NXOpen.NXMessageBox.DialogType.Warning,
                            "Введите запрос."
                        )
                        return 0

                    listing = self.theSession.ListingWindow
                    listing.Open()
                    listing.WriteLine("=" * 60)
                    listing.WriteLine(f"Запрос: {user_request}")
                    listing.WriteLine("Генерация запущена, ждите ответа от нейронки...")
                    listing.WriteLine("(может занять 1-3 минуты на локальной модели)")

                    python_exe = r"C:\Users\user\AppData\Local\Programs\Python\Python313\python.exe"
                    generate_script = r"C:\Users\user\Desktop\NX-3d-models\generate.py"
                    result_path = r"C:\Users\user\Desktop\NX-3d-models\generated\result.py"

                    proc = subprocess.run(
                        [python_exe, generate_script, user_request],
                        capture_output=True, text=True, encoding="utf-8", errors="replace",
                        timeout=900
                    )

                    if proc.returncode != 0:
                        listing.WriteLine("ОШИБКА при генерации:")
                        listing.WriteLine(proc.stdout)
                        listing.WriteLine(proc.stderr)
                        raise RuntimeError("generate.py завершился с ошибкой (см. Listing Window)")

                    listing.WriteLine("Генерация завершена, читаю result.py...")

                    with open(result_path, "r", encoding="utf-8") as f:
                        code = f.read()
                    exec(code, {})

                    listing.WriteLine("Готово: модель построена.")

                    self.theUI.NXMessageBox.Show(
                        "NX AI Generator", NXOpen.NXMessageBox.DialogType.Information,
                        "Модель построена"
                    )
                except Exception as ex:
                    self.theUI.NXMessageBox.Show(
                        "NX AI Generator", NXOpen.NXMessageBox.DialogType.Error, str(ex)
                    )
        except Exception as ex:
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return 0
    
    #------------------------------------------------------------------------------
    # Callback Name: ok_cb
    #------------------------------------------------------------------------------
    def ok_cb(self):
        errorCode = 0
        try:
            errorCode = self.apply_cb()
        except Exception as ex:
            errorCode = 1
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return errorCode
    
    #------------------------------------------------------------------------------
    # Function Name: GetBlockProperties
    #------------------------------------------------------------------------------
    def GetBlockProperties(self, blockID):
        try:
            return self.theDialog.GetBlockProperties(blockID)
        except Exception as ex:
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return None
    
def main():
    thenew_ui = None
    try:
        thenew_ui = new_ui()
        thenew_ui.Launch()
    except Exception as ex:
        NXOpen.UI.GetUI().NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
    finally:
        if thenew_ui != None:
            thenew_ui.Dispose()
            thenew_ui = None
    
if __name__ == '__main__':
    main()