#==============================================================================
#   WARNING!!  This file is overwritten by the Block UI Styler while generating
#   the automation code. Any modifications to this file will be lost after
#   generating the code again.
# 
#        Filename:  C:\Users\user\Desktop\AI_3D_NX_python_optimization_project\ui.py
# 
#         This file was generated by the NX Block UI Styler
#         Created by: user
#               Version: NX CAM 2406
#               Date: 08-12-2026  (Format: mm-dd-yyyy)
#               Time: 09:26 (Format: hh-mm)
# 
#==============================================================================

#==============================================================================
#   Purpose:  This TEMPLATE file contains Python source to guide you in the
#   construction of your Block application dialog. The generation of your
#   dialog file (.dlx extension) is the first step towards dialog construction
#   within NX.  You must now create a NX Open application that
#   utilizes this file (.dlx).
# 
#   The information in this file provides you with the following:
# 
#   1.  Help on how to load and display your Block UI Styler dialog in NX
#       using APIs provided in NXOpen.BlockStyler namespace
#   2.  The empty callback methods (stubs) associated with your dialog items
#       have also been placed in this file. These empty methods have been
#       created simply to start you along with your coding requirements.
#       The method name, argument list and possible return values have already
#       been provided for you.
#==============================================================================

#------------------------------------------------------------------------------
# These imports are needed for the following template code
#------------------------------------------------------------------------------
import NXOpen
import NXOpen.BlockStyler
import subprocess
#------------------------------------------------------------------------------
# Represents Block Styler application cls
#------------------------------------------------------------------------------
class ui:
    # static class members
    theSession = None
    theUI = None
    
    #------------------------------------------------------------------------------
    # Constructor for NX Styler class
    #------------------------------------------------------------------------------
    def __init__(self):
        try:
            self.theSession = NXOpen.Session.GetSession()
            self.theUI = NXOpen.UI.GetUI()
            self.theDlxFileName = r"C:\Users\Chelik\NX-3d-models\ui.dlx"
            self.theDialog = self.theUI.CreateDialog(self.theDlxFileName)
            self.theDialog.AddApplyHandler(self.apply_cb)
            self.theDialog.AddOkHandler(self.ok_cb)
            self.theDialog.AddUpdateHandler(self.update_cb)
            self.theDialog.AddInitializeHandler(self.initialize_cb)
            self.theDialog.AddDialogShownHandler(self.dialogShown_cb)
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            raise ex
        
    
    # ------------------------------- DIALOG LAUNCHING ---------------------------------
    # 
    #     Before invoking this application one needs to open any part/empty part in NX
    #     because of the behavior of the blocks.
    # 
    #     Make sure the dlx file is in one of the following locations:
    #         1.) From where NX session is launched
    #         2.) $UGII_USER_DIR/application
    #         3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    #             recommended. This variable is set to a full directory path to a file 
    #             containing a list of root directories for all custom applications.
    #             e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    # 
    #     You can create the dialog using one of the following way:
    # 
    #     1. Journal Replay
    # 
    #         1) Replay this file through Tool->Journal->Play Menu.
    # 
    #     2. USER EXIT
    # 
    #         1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    #         2) Invoke the Shared Library through File->Execute->NX Open menu.
    # 
    #------------------------------------------------------------------------------
    
    #------------------------------------------------------------------------------
    # This method launches the dialog to screen
    #------------------------------------------------------------------------------
    def Launch(self):
        dialogResponse = NXOpen.BlockStyler.BlockDialog.DialogResponse.Invalid
        try:
            dialogResponse = self.theDialog.Launch()
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return dialogResponse
    
    #------------------------------------------------------------------------------
    # Method Name: Dispose
    #------------------------------------------------------------------------------
    def Dispose(self):
        if self.theDialog != None:
            self.theDialog.Dispose()
            self.theDialog = None
    
    #------------------------------------------------------------------------------
    # ---------------------Block UI Styler Callback Functions--------------------------
    #------------------------------------------------------------------------------
    
    #------------------------------------------------------------------------------
    # Callback Name: initialize_cb
    #------------------------------------------------------------------------------
    def initialize_cb(self):
        try:
            self.group0 = self.theDialog.TopBlock.FindBlock("group0")
            self.string = self.theDialog.TopBlock.FindBlock("string")
            self.button = self.theDialog.TopBlock.FindBlock("button")
            #------------------------------------------------------------------------------
            # Registration of StringBlock specific callbacks
            #------------------------------------------------------------------------------
            # self.string.SetKeystrokeCallback(self.KeystrokeCallback)
            
            #------------------------------------------------------------------------------
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
    
    #------------------------------------------------------------------------------
    # Callback Name: dialogShown_cb
    # This callback is executed just before the dialog launch. Thus any value set 
    # here will take precedence and dialog will be launched showing that value. 
    #------------------------------------------------------------------------------
    def dialogShown_cb(self):
        try:
            # ---- Enter your callback code here -----
            pass
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
    
    #------------------------------------------------------------------------------
    # Callback Name: apply_cb
    #------------------------------------------------------------------------------
    def apply_cb(self):
        errorCode = 0
        try:
            # ---- Enter your callback code here -----
            pass
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            errorCode = 1
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return errorCode
    
    #------------------------------------------------------------------------------
    # Callback Name: update_cb
    #------------------------------------------------------------------------------
    def update_cb(self, block):
        try:
            if block == self.string:
                pass
            elif block == self.button:
                try:
                    user_request = self.string.Value.strip()
                    if not user_request:
                        self.theUI.NXMessageBox.Show(
                            "NX AI Generator", NXOpen.NXMessageBox.DialogType.Warning,
                            "Введите запрос."
                        )
                        return 0

                    listing = self.theSession.ListingWindow
                    listing.Open()
                    listing.WriteLine("=" * 60)
                    listing.WriteLine(f"Запрос: {user_request}")
                    listing.WriteLine("Генерация запущена, ждите ответа от нейронки...")
                    listing.WriteLine("(может занять 1-3 минуты на локальной модели)")

                    python_exe = r"C:\Python313\python.exe"
                    generate_script = r"C:\Users\Chelik\NX-3d-models\generate.py"
                    result_path = r"C:\Users\Chelik\NX-3d-models\generated\result.py"

                    proc = subprocess.run(
                        [python_exe, generate_script, user_request],
                        capture_output=True, text=True, encoding="utf-8", errors="replace",
                        timeout=900
                    )

                    if proc.returncode != 0:
                        listing.WriteLine("ОШИБКА при генерации:")
                        listing.WriteLine(proc.stdout)
                        listing.WriteLine(proc.stderr)
                        raise RuntimeError("generate.py завершился с ошибкой (см. Listing Window)")

                    listing.WriteLine("Генерация завершена, читаю result.py...")

                    with open(result_path, "r", encoding="utf-8") as f:
                        code = f.read()
                    exec(code, {})

                    listing.WriteLine("Готово: модель построена.")

                    self.theUI.NXMessageBox.Show(
                        "NX AI Generator", NXOpen.NXMessageBox.DialogType.Information,
                        "Модель построена"
                    )
                except Exception as ex:
                    self.theUI.NXMessageBox.Show(
                        "NX AI Generator", NXOpen.NXMessageBox.DialogType.Error, str(ex)
                    )
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return 0
    
    #------------------------------------------------------------------------------
    # Callback Name: ok_cb
    #------------------------------------------------------------------------------
    def ok_cb(self):
        errorCode = 0
        try:
            # ---- Enter your callback code here -----
            errorCode = self.apply_cb()
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            errorCode = 1
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return errorCode
    
    #------------------------------------------------------------------------------
    # StringBlock specific callbacks
    #------------------------------------------------------------------------------
    # def KeystrokeCallback (self, stringBlock, uncommittedValue):
    # 
    # 
    
    #------------------------------------------------------------------------------
    
    #------------------------------------------------------------------------------
    # Function Name: GetBlockProperties
    # Returns the propertylist of the specified BlockID
    #------------------------------------------------------------------------------
    def GetBlockProperties(self, blockID):
        try:
            return self.theDialog.GetBlockProperties(blockID)
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return None
    
def main():
    theui = None
    try:
        theui =  ui()
        #  The following method shows the dialog immediately
        theui.Launch()
    except Exception as ex:
        # ---- Enter your exception handling code here -----
        NXOpen.UI.GetUI().NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
    finally:
        if theui != None:
            theui.Dispose()
            theui = None
    
if __name__ == '__main__':
    main()

